### ISSUE TITLE
A little query

### ISSUE THREAD

**Issue by hashirali2604** [EvilPort2/Hand-Tracking#1]
Dear Dibakar Saha glad to see your work and thanks alot for sharing it with others... I would like to know just a few things if you assist me kindly... Actually I'm too new to these deep learning things and all that, so I'm doing a project that needs dental instruments detection (object recognition) for 11 objects with the labels that will be performed finally on pi... I have already tried a yolo model for that but unfortunately end up detecting nothing or sometimes with a very low confidence... Did you please just guide me how can I use your repo for my project? Also I made videos for my objects and further breakdown into frames and hence made my dataset of around 16,000 and annotate them in .xml files...

**Comment by galvinw** [comment]
This is not a yolo model. You're looking for this https://github.com/AlexeyAB/darknet

**Comment by hashirali2604** [comment]
@galvinw sir I'm not looking for yolo model I simply asked is this repo help me in detecting objects or not? Kindly read my issue again 😢

**Comment by EvilPort2** [comment]
@hashirali2604 Follow the tutorial by sentdex here https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/

**Comment by hashirali2604** [comment]
@EvilPort2 okay sir 👍
